### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by Xixo99** [freepower311/PLDA_speaker_verification#1]
hi,  I hope to learn more about your code.
Can you tell me your PLDA formula? 
I didn't see the algorithm of EM step in your code, so there was some trouble. 
I hope you can write one readme.md To help understand. thank you!

**Comment by freepower311** [comment]
Hi, this code is no longer maintained. I can't remember what exactly it does. It is mainly based on this [article](http://www.fit.vutbr.cz/research/groups/speech/publi/2011/cumani_icassp2011_4852.pdf). If I remember correct here I compare the hinge loss function and the logical loss function in task of speaker verification.

**Comment by Xixo99** [comment]
thank you very much

**Comment by freepower311** [comment]
I also created [wiki page](https://github.com/freepower311/PLDA_speaker_verification/wiki) based on my explanation in my paper work. This work is in Russian and it is far from perfect, so I do not want to post it completely.
